nelmio_api_doc:
    documentation:
        info:
            title: Study-On.Billing
            description: Billing service for study-on!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        default:
            path_patterns:
                - ^/api/v1